andresramosn/boost_it

app/controllers/application_controller.rb
app/views/devise/confirmations/new.html.erb
app/views/devise/mailer/confirmation_instructions.html.erb
app/views/devise/mailer/email_changed.html.erb
app/views/devise/mailer/password_change.html.erb
app/views/devise/mailer/reset_password_instructions.html.erb
app/views/devise/mailer/unlock_instructions.html.erb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_error_messages.html.erb
app/views/devise/shared/_links.html.erb
app/views/devise/unlocks/new.html.erb
config/environments/development.rb
db/migrate/20191210113536_create_shares.rb
db/migrate/20191210162550_add_username_to_user.rb
db/schema.rb

User registration login

---

app/controllers/lists_controller.rb
app/views/lists/new.html.erb

Add a list and a tip

---

app/assets/stylesheets/components/_web-container.scss
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/lists/index.html.erb
config/routes.rb

fix - small changes

---

app/views/lists/index.html.erb

fix - fixed route

---

app/views/lists/index.html.erb

fix - add tip

---

app/assets/stylesheets/components/_button-container.scss
app/assets/stylesheets/components/_list-card.scss
app/views/lists/index.html.erb
app/views/tips/new.html.erb

first version of list cards completed

---

app/controllers/lists_controller.rb
app/controllers/tips_controller.rb
app/controllers/tips_lists_controller.rb
app/views/lists/index.html.erb
app/views/lists/show.html.erb
app/views/tips/index.html.erb
app/views/tips/new.html.erb
app/views/tips_lists/create.html.erb
app/views/tips_lists/new.html.erb
config/routes.rb
test/controllers/tips_lists_controller_test.rb

List=index css

---

app/controllers/tips_lists_controller.rb
app/views/tips_lists/show.html.erb

completed controller

---

app/controllers/tips_lists_controller.rb
app/javascript/components/photo_preview.js
app/views/lists/index.html.erb
app/views/tips/index.html.erb
app/views/tips/new.html.erb
app/views/tips_lists/new.html.erb

images fixed

---

app/views/tips/new.html.erb

list dropdown display

---

app/assets/stylesheets/components/_pill-category.scss
app/models/tip.rb
app/views/lists/show.html.erb
app/views/tips/index.html.erb

pills with responsive colors

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_lists.scss
app/javascript/components/tabs.js
app/javascript/packs/application.js
app/views/lists/index.html.erb

tabs added

---

app/assets/stylesheets/components/_lists.scss
app/javascript/components/tabs.js
app/views/lists/index.html.erb

we can see the shared ones

---

app/views/lists/index.html.erb

please review, and if there are conflicts let me know :)

index of the list fixed, please mantain it like this. this is the bible

---

app/assets/stylesheets/components/_lists.scss
app/javascript/components/tabs.js
app/javascript/packs/application.js
app/views/lists/index.html.erb
app/views/tips/index.html.erb

review, please be careful with the index is well indented.

Colors tab

---

app/assets/stylesheets/components/_home-container.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_logotype.scss
app/assets/stylesheets/components/_main-button.scss
app/assets/stylesheets/components/_second-section-home.scss
app/views/pages/home.html.erb

small fixes to homepage

---

app/assets/stylesheets/components/_second-section-home.scss
app/javascript/plugins/fetch_places.js
app/views/pages/home.html.erb

Homepage design

---

app/assets/stylesheets/components/_btn-map.scss
app/assets/stylesheets/components/_map.scss
app/assets/stylesheets/components/_photo-show-page.scss
app/assets/stylesheets/components/_pill-category.scss
app/assets/stylesheets/components/_settings.scss
app/javascript/plugins/toggle_map.js
app/views/lists/index.html.erb
app/views/lists/show.html.erb
app/views/tips/all_tips.html.erb
app/views/tips/index.html.erb
app/views/tips/show.html.erb

review porfii, está todo el temal del mapa en el show, botón etc solved! ;)

Fix your lists index

---

app/views/lists/index.html.erb
app/views/lists/show.html.erb
app/views/tips/index.html.erb
app/views/tips_lists/new.html.erb

Last changes

---

app/assets/stylesheets/components/_home-container.scss
app/assets/stylesheets/components/_main-button.scss
app/assets/stylesheets/components/_second-section-home.scss
app/views/pages/home.html.erb

Homepage final design

---

app/assets/stylesheets/components/_add-button.scss
app/assets/stylesheets/components/_logotype.scss
app/views/lists/index.html.erb

List index design

---

app/views/lists/show.html.erb
app/views/tips/show.html.erb

indentation and avatar added

---

app/views/tips/index.html.erb

fix - indentation

---

app/views/lists/new.html.erb

New list form

---

app/views/tips/new.html.erb

fix -indentation

---

app/views/lists/show.html.erb
app/views/tips/index.html.erb
app/views/tips_lists/new.html.erb

fix -aligned design

---

app/views/shares/index.html.erb

fix aligned design

---

app/views/shares/index.html.erb
app/views/shares/new_guest.html.erb

fix - aligned design

---

app/assets/stylesheets/components/_guest-card.scss
app/views/shares/index.html.erb
app/views/tips/all_tips.html.erb

Guest show

---

app/assets/stylesheets/components/_guest-card.scss
app/assets/stylesheets/components/_lists.scss
app/views/shares/index.html.erb

Fe your guests

---

app/controllers/tips_lists_controller.rb
app/views/lists/index.html.erb
app/views/lists/show.html.erb
app/views/tips/add_to_list.html.erb
app/views/tips/all_tips.html.erb
app/views/tips/index.html.erb
app/views/tips/new.html.erb
app/views/tips_lists/new.html.erb

Google pic

---

app/views/shares/invite_url.html.erb

congratulations page fixed

---

app/javascript/components/remove_google_pic.js
app/javascript/packs/application.js
app/views/lists/index.html.erb
app/views/shares/show.html.erb
app/views/tips/add_to_list.html.erb
app/views/tips/index.html.erb
app/views/tips/new.html.erb
app/views/tips_lists/new.html.erb

Last fixes
